supabase-community/launchweek.dev

README.md

feature: adding a link to sentry's launch week 

feat: add sentry launch week

---

README.md

add revert.dev launch week

---

README.md

This PR adds Inngest Launch week to the list.
Thank you for running this site!

Add Inngest to the list

---

README.md

Bug fix, feature, docs update, ...

feat: add loops launch week

---

README.md

Update Highlight.io Launch Week 4 page

---

README.md

Thank you for your efforts..
Let me know if I missed anything.. :)

Add MilkStraw AI launch week

---

README.md

Karrio Launch Week
2024 / 03 / 11-15
https://karrio.io/

Add Karrio Launch Week

---

README.md

Postponing Karrio Launch week to March 18

Update Karrio Launch Week

---

README.md

Super excited to join the party 🎉
PS: Updated the upcoming launch weeks

Add Firecrawl's first launch week 🔥

---

README.md

Added Daytona to the list and up the counter.

Add Daytona Launch Week

---

README.md

Add Impler Launch Week

---

README.md

New product launch week for Glasskube

website(readme): added glasskube launch week

---

README.md

Hey! added some links, hope it is fine. Tnx :-D

Added links to Daytona Launch Week

---

README.md

Hey, 
hope this is fine. Shout if not. :D
Thanks,
Niko

Add Daytona Launch Week #2

---

README.md

Add Permit Launch Week
Missing link
Added link

Add Permit Launch Week

---

README.mdx

Bug fix, feature, docs update, ...

Updated Trigger.dev lw dates to be more mega

---

README.mdx

Added Quivr to the launchweek :)

feat(quivr): added to launchweek

---

README.mdx
lw/2024.mdx
lw/INDEX.mdx

Adding the first Cyclops launch week with the link to our LinkedIn announcement

Add Cyclops Launch Week

---

HOME.mdx

This adds Jamsocket as a launch week participant. Looking forward to launching with y'all!

Add Jamsocket Launch Week

---

HOME.mdx

Added Speakeasy Launch Week 0 for 02-06 December

Add Speakeasy to mega launch week

---

HOME.mdx
README.md
lw/2024.mdx
lw/INDEX.mdx

Including Outerbase in the upcoming Mega Launch Week
Bug fix, feature, docs update, ...

Include Outerbase launch week

---

HOME.mdx

Add Laminar launch week for 2024-12-02--06

add Laminar launch week

---

lw/2024.mdx

Added Ellipsis (www.ellipsis.dev/launch-week) and updated total counts.

Add Ellipsis Launch Week

---

HOME.mdx
README.md
lw/2024.mdx
lw/INDEX.mdx

Updated the same 4 files as the other PRs but let me know please if I missed anything :)

Add Andi to launch week, dec 2

---

HOME.mdx
README.md
lw/2024.mdx
lw/INDEX.mdx

updated the 4 files. let me know if I missed anything!

Add AirPinpoint Launch Week

---

HOME.mdx
README.md
lw/2024.mdx
lw/INDEX.mdx

Please let me know if I missed anything -- so excited for Mega Launch Week!

Add KeyHippo Launch Week

---

lw/2024.mdx
lw/INDEX.mdx
lw/MEGA.mdx

Add beam.cloud Launch Week

---

README.md
lw/2024.mdx
lw/INDEX.mdx
lw/MEGA.mdx

Added Replexica to mega launch md files and README.

Add Replexica to mega launch week

---

README.md

Added Fiberplane to MEGA launchweek

Add Fiberplane to launchweek

---

lw/MEGA.mdx

Update MEGA.mdx with Fiberplane as participant

---

lw/MEGA.mdx

Hey @fmerian we launched from my X account today since the [KeyHippo](https://x.com/keyhippo) account was still going through verification this morning. Looks like it went through so I'll post lw updates from there for the rest of the week. I also intend to participate in the [Product Hunt Battle Royale](https://launchweek.dev/lw/MEGA#announcements). Good luck everyone!

Add KeyHippo to Day 1 Recap

---

lw/MEGA.mdx

Add Magic Patterns LW Day 2

---

lw/MEGA.mdx

Bug fix, feature, docs update, ...

adding openint thursday announcement

---

README.md
home.mdx
lw/2024.mdx
lw/index.mdx

- Read the blog announcement: https://www.morph-data.io/blog/launch-week-2
- Preview on X: https://x.com/morphdbHQ/status/1868592478334722377

Add Morph Launch Week 2

---

home.mdx
humans.txt
lw/2024.mdx
mint.json
n/fmerian.mdx
n/forward.mdx
n/kiwicopple.mdx
n/resend.mdx
n/rorstro.mdx
n/supabase.mdx

This update includes:
- New layout for product discovery
- Link to Resend's Handbook (must-read)

2024-12 W51 updates

---

home.mdx
lw/2024.mdx

Hey,
sorry for the last minute, but we were eager to push this and squeeze one more in 2024. :-D
Hopefully, I did everything right this time?
Best

Add Daytona Launch Week 4

---

README.md
home.mdx
lw/2025.mdx

Add SigNoz Launch Week 3

---

README.md
home.mdx
lw/2025.mdx

Add Pullpo Launch Week

---

README.md
home.mdx
lw/2025.mdx

Added Laravel launch week.
Thanks!

Add Laravel Launch Week

---

README.md
home.mdx
lw/2025.mdx

https://tinybird.co/forward-launch

Add Tinybird Forward Launch Week

---

README.md
home.mdx
lw/2025.mdx

https://www.nango.dev/launch-week

Add Nango Launch Week

---

README.md
home.mdx

Add [Meilisearch](https://meilisearch.com/launch-week) Launch Week to the calendar

Add Meilisearch Launch Week

---

README.md
home.mdx
lw/2025.mdx

Added Agenta Launch Week 1 to the list of launch weeks

Add Agenta Launch Week 1

---

README.md
home.mdx
lw/2025.mdx

feat: Daytona Create Launch Week 6

---

README.md
home.mdx
lw/2025.mdx

https://supabase.com/launch-week

Add Supabase Launch Week 15

---

README.md
home.mdx
lw/2025.mdx

#162 
https://postgres.ai/launch-week

Add Postgres AI Launch Week
